[project]
name = "issue18469"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["django>=5.1.3"]

[dependency-groups]
dev = ["django-stubs[compatible-mypy]>=5.1.1", "django-types>=0.19.1"]
